// ============================================================
// PROPERTY DATA
// ------------------------------------------------------------
// This is the file you'll edit as properties come and go.
// Each listing is one object in the LISTINGS array below.
//
// FIELD REFERENCE:
//   id        - unique slug, e.g. "48-case-rd-burlington-ct"
//   address   - street address
//   town      - town/city name
//   state     - "CT" or "MA"
//   price     - number, no $ or commas (current asking price)
//   originalPrice - number, optional. Set this if the price has been cut
//               since you first saw it. Omit it entirely if there's been
//               no change — don't set it equal to price.
//   lat, lng  - decimal coordinates, used for the Map tab. Easiest way to
//               get these: right-click the spot on Google Maps and click
//               the coordinates that pop up at the top — it copies them.
//   imageUrl  - optional. Direct link to the listing's first photo. On a
//               Zillow page, right-click the first photo and "Copy image
//               address" — or ask Claude to pull it from the og:image tag.
//               Omit if you don't have one; the card just skips the photo.
//   beds      - number
//   baths     - number
//   sqft      - number
//   acres     - number (decimal ok)
//   type      - free text, e.g. "Single family", "Cape"
//   status    - "active" | "pending" | "contingent" | "sold"
//   listedDate- "YYYY-MM-DD"
//   hvac      - "central" | "minisplit" | "window" | "none"
//               (central/minisplit = good, window = warning, none = bad)
//   flags     - array of short strings, e.g. ["unpermitted addition"]
//   url       - listing URL (Zillow/Realtor.com/etc.)
//   notes     - free text, shows on the card
//   watchlist - true/false — whether this is a saved favorite
//   dismissed - true/false — whether this has been passed on
//   lastChecked - "YYYY-MM-DD", optional. The date you (or Claude) last
//               confirmed this listing's status directly on Zillow/Realtor.
//               Cards flag themselves once this gets older than 14 days —
//               a direct response to a couple of stale reads that caused
//               confusion this week.
// ============================================================

const LISTINGS = [
  {
    id: "101-abbey-rd-east-hampton-ct",
    address: "101 Abbey Rd",
    town: "East Hampton",
    state: "CT",
    price: 439900,
    lat: 41.5734,
    lng: -72.4979,
    imageUrl: "https://photos.zillowstatic.com/fp/583d29cbeae84bdc3d1c73a101fa0852-cc_ft_960.webp",
    beds: 4,
    baths: 2,
    sqft: 2427,
    acres: 1.06,
    type: "Cape",
    status: "sold",
    listedDate: "2026-07-16",
    hvac: "window",
    flags: ["Strong interest — 1,578 views / 126 saves as of day 2", "Now pending as of 7/27", "Changed to accepting backups as of 7/30", "SOLD as of 8/27"],
    url: "https://www.zillow.com/homedetails/101-Abbey-Rd-East-Hampton-CT-06424/57853768_zpid/",
    notes: "Cape near Middletown. Main floor bed+bath, upstairs primary + 2 more beds. New septic + updated electrical. Window units only, mini-splits needed. Note: Zillow briefly showed this as off-market on 7/18 — confirmed still active; Zillow status/Zestimate can lag a few days.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-27"
  },
  {
    id: "181-moulton-hill-rd-monson-ma",
    address: "181 Moulton Hill Rd",
    town: "Monson",
    state: "MA",
    price: 539800,
    lat: 42.0995,
    lng: -72.3162,
    imageUrl: "https://photos.zillowstatic.com/fp/9de4311b17c455f636f6c9f82541f7ba-cc_ft_960.webp",
    beds: 4,
    baths: 2,
    sqft: 2047,
    acres: 2,
    type: "Colonial",
    status: "contingent",
    listedDate: "2026-07-15",
    hvac: "central",
    flags: ["Move fast — will go quickly", "Under contract as of 7/20 — went fast as expected"],
    url: "https://www.zillow.com/homedetails/181-Moulton-Hill-Rd-Monson-MA-01057/193645908_zpid/",
    notes: "Built 2009, clean modern systems. Perfect split: 2BR/1BA first floor + 2BR/1BA second floor. Central air. Walkout basement unfinished. 2-car garage + 6 parking. Taxes $6,760/yr.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-07-20"
  },
  {
    id: "67-bell-st-middletown-ct",
    address: "67 Bell St",
    town: "Middletown",
    state: "CT",
    price: 499900,
    lat: 41.5623,
    lng: -72.6506,
    imageUrl: "https://photos.zillowstatic.com/fp/99036c74697e2b0b08c21a1d4806caa2-cc_ft_1536.jpg",
    beds: 3,
    baths: 2,
    sqft: 1576,
    acres: 4.6,
    type: "Single family",
    status: "pending",
    listedDate: "2026-06-23",
    hvac: "none",
    flags: ["Verify solar if it relists", "Under contract as of 8/3 — removed from active consideration"],
    url: "https://www.zillow.com/homedetails/67-Bell-St-Middletown-CT-06457/57866674_zpid/",
    notes: "Good separation: main floor primary + 1BR, lower level 1BR w/ own full bath. Right in Middletown. 4.6 acres, barn/stable. Sold $248k in 2019 → $499,900 now. No central air. Unpermitted/undisclosed solar — verify owned vs leased. Taxes $8,421/yr.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-03"
  },
  {
    id: "48-case-rd-burlington-ct",
    address: "48 Case Rd",
    town: "Burlington",
    state: "CT",
    price: 469000,
    originalPrice: 489000,
    lat: 41.7615,
    lng: -72.9587,
    imageUrl: "https://photos.zillowstatic.com/fp/f360f35d884f0ca0e40b6ed6493c1112-cc_ft_1536.jpg",
    beds: 4,
    baths: 3,
    sqft: 1929,
    acres: 1.02,
    type: "Colonial",
    status: "pending",
    listedDate: "2026-06-18",
    hvac: "central",
    flags: ["Deal fell through — ask why", "Under contract as of 8/3 — removed from active consideration"],
    url: "https://www.zillow.com/homedetails/48-Case-Rd-Burlington-CT-06013/57706189_zpid/",
    notes: "2BR/2BA main floor — natural two-person separation. 2BR/1BA upstairs bonus space. Oil forced air + central air. Solar — verify owned vs PPA/leased. Reactivated after prior contract fell through.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-03"
  },
  {
    id: "235-middle-haddam-rd-east-hampton-ct",
    address: "235 Middle Haddam Rd",
    town: "East Hampton",
    state: "CT",
    price: 479900,
    lat: 41.5734,
    lng: -72.4979,
    imageUrl: "https://photos.zillowstatic.com/fp/2a68c6fd99ac9f96795141ff2e234fe3-cc_ft_1536.jpg",
    beds: 4,
    baths: 2,
    sqft: 1923,
    acres: 1.2,
    type: "Log Cabin",
    status: "sold",
    listedDate: "2026-06-13",
    hvac: "central",
    flags: ["Run permit check first", "SOLD as of 8/18"],
    url: "https://www.zillow.com/homedetails/235-Middle-Haddam-Rd-E-Middle-Haddam-CT-06456/463217927_zpid/",
    notes: "Log cabin construction, two stone fireplaces, wraparound porch. Detached 2-car garage w/ loft + heater — workshop potential. Next to Hurd State Park, ~15-18 min to Middletown. Main level 2BR/1BA + upper 2BR/1BA. Central air + whole-house Generac. Taxes $7,400/yr. Accepting backups.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-18"
  },
  {
    id: "3-gretl-ln-new-milford-ct",
    address: "3 Gretl Ln",
    town: "New Milford",
    state: "CT",
    price: 479000,
    lat: 41.5793,
    lng: -73.4087,
    imageUrl: "https://photos.zillowstatic.com/fp/4f2aff2770ad6612ab8e8212044265fd-cc_ft_1536.jpg",
    beds: 4,
    baths: 2,
    sqft: 1908,
    acres: 1.08,
    type: "Raised Ranch",
    status: "pending",
    listedDate: "2026-06-07",
    hvac: "window",
    flags: ["Accepting backups — watch for relist", "Now pending as of 7/27, no longer just contingent", "Confirmed under contract as of 7/30", "Under contract as of 8/3 — removed from active consideration"],
    url: "https://www.zillow.com/homedetails/3-Gretl-Ln-New-Milford-CT-06776/58863029_zpid/",
    notes: "Built 1975, updated interior, refinished hardwoods. Lower level 12x15 BR + family room walkout. New furnace + HWH. Near Candlewood Lake. 2020 sale had same contingent→fall-through→relist pattern. Window units, mini-splits needed ~$18-25k.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-03"
  },
  {
    id: "200-bucks-hill-rd-southbury-ct",
    address: "200 Bucks Hill Rd",
    town: "Southbury",
    state: "CT",
    price: 499900,
    lat: 41.4837,
    lng: -73.2098,
    imageUrl: "https://photos.zillowstatic.com/fp/57b38a8ced25bbd30a235cb98cc95434-cc_ft_1536.jpg",
    beds: 3,
    baths: 2,
    sqft: 2360,
    acres: 1.53,
    type: "Cape",
    status: "sold",
    listedDate: "2026-05-28",
    hvac: "window",
    flags: ["Accepting backups", "SOLD as of 7/27"],
    url: "https://www.zillow.com/homedetails/200-Bucks-Hill-Rd-Southbury-CT-06488/57991955_zpid/",
    notes: "3-level Cape — main floor primary suite, upper 2 large beds + full bath, basement family room. New 3-zone Burnham boiler. New roof 2022. Failed at $479,900 in 2023. Window units, mini-splits needed ~$15-25k.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-07-27"
  },
  {
    id: "143-belleview-ave-southington-ct",
    address: "143 Belleview Ave",
    town: "Southington",
    state: "CT",
    price: 539900,
    lat: 41.5998,
    lng: -72.8781,
    imageUrl: "https://photos.zillowstatic.com/fp/182e73de1b9a04e11b9666b4a58b44b0-cc_ft_1536.jpg",
    beds: 3,
    baths: 2,
    sqft: 2148,
    acres: 1.09,
    type: "Cape",
    status: "withdrawn",
    listedDate: "2026-06-05",
    hvac: "central",
    flags: ["Check layout — photos now live", "REMOVED 8/24: Off market — seller gave up after a $40k price drop"],
    url: "https://www.zillow.com/homedetails/143-Belleview-Ave-Southington-CT-06489/174097245_zpid/",
    notes: "Built 1954, 1.09 acres. Natural gas + central air — best fuel combo. All bedrooms upstairs — layout concern for two-person separation.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-24"
  },
  {
    id: "541-middlebury-rd-watertown-ct",
    address: "541 Middlebury Rd",
    town: "Watertown",
    state: "CT",
    price: 499900,
    lat: 41.6032,
    lng: -73.1187,
    imageUrl: "https://photos.zillowstatic.com/fp/96b057c422d21863764e308fad556903-cc_ft_1536.jpg",
    beds: 4,
    baths: 4,
    sqft: 2496,
    acres: 1.04,
    type: "Colonial",
    status: "withdrawn",
    listedDate: "2026-05-23",
    hvac: "central",
    flags: ["Septic from 2002 — 24 years old, Title V inspection required at sale", "If septic fails: replacement $15-30k — seller-paid new septic should be a condition of any offer", "Water district matters — Watertown Fire District preferred over Waterbury municipal, verify which serves this address", "First contract likely fell through on septic or inspection findings", "If backup position opens: negotiate price drop + seller-paid septic replacement", "Watch for further price reduction if current deal collapses", "68 days on market, now Accepting Backups as of 7/30", "Seller withdrew the listing as of 8/20 — gave up on selling"],
    url: "https://www.zillow.com/homedetails/541-Middlebury-Rd-Watertown-CT-06795/58870675_zpid/",
    notes: "Colonial, central air. Masonry fireplace, hardwood throughout, French doors. Good separation — primary suite upstairs, finished lower level with full bath + walkout. Oil baseboard heat.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-20"
  },
  {
    id: "80-old-baird-rd-watertown-ct",
    address: "80 Old Baird Rd",
    town: "Watertown",
    state: "CT",
    price: 525000,
    lat: 41.6032,
    lng: -73.1187,
    imageUrl: "https://photos.zillowstatic.com/fp/3947fc2eb10d03b3f35bb94e58800cb5-cc_ft_1536.jpg",
    beds: 3,
    baths: 3,
    sqft: null,
    acres: 1.78,
    type: "Craftsman Cape",
    status: "pending",
    listedDate: "2026-05-23",
    hvac: "central",
    flags: ["Pending as of Thursday 7/16 — off the table"],
    url: "https://www.zillow.com/homedetails/80-Old-Baird-Rd-Watertown-CT-06795/197756999_zpid/",
    notes: "Viking appliances, stone fireplace, cathedral ceilings. Each upstairs bedroom has own en-suite bath. Main floor 3rd bed + full bath. Propane baseboard + central air. Dead-end road, 1.78 acres. Accepting backups — watch for relist.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-07-18"
  },
  {
    id: "392-boston-neck-rd-suffield-ct",
    address: "392 Boston Neck Rd",
    town: "Suffield",
    state: "CT",
    price: 349900,
    originalPrice: 399900,
    lat: 41.9812,
    lng: -72.6482,
    imageUrl: "https://photos.zillowstatic.com/fp/1b4bbf0b5d50fdc925ec594668fc17fc-cc_ft_1536.jpg",
    beds: 4,
    baths: 2,
    sqft: 2444,
    acres: 1.32,
    type: "Antique Colonial",
    status: "active",
    listedDate: "2026-03-15",
    hvac: "central",
    flags: ["1755 origin — inspect carefully", "$50K cut 8/18: $399.9k → $349.9k", "REMOVED 8/24: Partner doesn't love it"],
    url: "https://www.zillow.com/homedetails/392-Boston-Neck-Rd-Suffield-CT-06078/59024451_zpid/",
    notes: "Built 1755 original, substantially renovated. $40k drop — likely long-term family estate. Clean permit history — all Complete in ViewMyPermitCT. Oil hot water + central air.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-24"
  },
  {
    id: "76-clark-hill-rd-prospect-ct",
    address: "76 Clark Hill Rd",
    town: "Prospect",
    state: "CT",
    price: 499000,
    lat: 41.5029,
    lng: -72.9662,
    imageUrl: "https://photos.zillowstatic.com/fp/bfff281da1f881dce29f36f4c1ac39ee-cc_ft_960.webp",
    beds: 4,
    baths: 3,
    sqft: 3150,
    acres: 2.03,
    type: "Single family",
    status: "pending",
    listedDate: "2026-02-15",
    hvac: "central",
    flags: ["Now pending", "REMOVED 8/24: Pending, removed from active consideration"],
    url: "https://www.zillow.com/homedetails/76-Clark-Hill-Rd-Prospect-CT-06712/57985177_zpid/",
    notes: "Level lot, 2+ acres, 2-car garage, 3,150 sqft — needs renovation. Oil hot air + central air. Sitting on market.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-24"
  },
  {
    id: "55-southampton-rd-westhampton-ma",
    address: "55 Southampton Rd",
    town: "Westhampton",
    state: "MA",
    price: 499900,
    originalPrice: 525000,
    lat: 42.2626,
    lng: -72.7534,
    imageUrl: "https://photos.zillowstatic.com/fp/fcb7c64326c1649d88a9b827b3040588-cc_ft_960.webp",
    beds: 4,
    baths: 2,
    sqft: 1944,
    acres: 1.21,
    type: "Single family",
    status: "active",
    listedDate: "2026-06-20",
    hvac: "window",
    flags: ["Verify ownership history", "$25.1K cut 8/21: $525k → $499.9k", "REMOVED 8/24: Partner doesn't love the location"],
    url: "https://www.zillow.com/homedetails/55-Southampton-Rd-Westhampton-MA-01027/57028999_zpid/",
    notes: "Brook access, greenhouse, gardens, dog run. 2BR main floor incl. primary suite + 1BR upstairs — reasonable separation. Taxes only $5,572/yr, near Northampton. Electric heat + pellet stoves, window units only. Listed 2018 at $339,900 (didn't sell), no recorded sale since — ask agent about ownership gap.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-24"
  },
  {
    id: "68-lyon-rd-west-brookfield-ma",
    address: "68 Lyon Rd",
    town: "West Brookfield",
    state: "MA",
    price: 430000,
    originalPrice: 525000,
    lat: 42.2382,
    lng: -72.1512,
    imageUrl: "https://photos.zillowstatic.com/fp/154e75b246dd49eb835d06a54c0d6534-cc_ft_960.webp",
    beds: 3,
    baths: 2,
    sqft: 2280,
    acres: 1.81,
    type: "Single family w/ ADU",
    status: "active",
    listedDate: "2026-06-14",
    hvac: "none",
    flags: ["Not move-in ready — bare subfloor, unfinished drywall in photos", "Electric heat — needs full heat pump/mini-split overhaul ~$20-30k", "Odd exterior aesthetic", "68+ days on market even after cuts — watch if others look and pass to gauge hidden issues", "$65k cut on 7/28 ($495k → $430k) — finally in consideration range", "Will take a ton of cash to fix up. If it drops under $400k, might be interested."],
    url: "https://www.zillow.com/homedetails/68-Lyon-Rd-West-Brookfield-MA-01585/57673905_zpid/",
    notes: "ADU-style layout — upper level 3BR + half bath + kitchen/living, lower level BR + full bath + kitchenette + 2 bonus rooms. Heated 3-car detached garage — excellent workshop/studio potential. Ware 9 min. Taxes $3,866/yr — one of the lowest on the list.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-08-24"
  },
  {
    id: "1130-main-dalton-rd-windsor-ma",
    address: "1130 Main Dalton Rd",
    town: "Windsor",
    state: "MA",
    price: 474900,
    lat: 42.5262,
    lng: -73.0231,
    imageUrl: "https://photos.zillowstatic.com/fp/4d7e0a71811ab80dcb28ec75895732f6-cc_ft_960.webp",
    beds: 4,
    baths: 2,
    sqft: 2616,
    acres: 9.11,
    type: "Single family",
    status: "sold",
    listedDate: "2026-06-10",
    hvac: "none",
    flags: ["Panel upgrade + mini-splits needed", "Now pending as of 7/27", "SOLD as of 8/12"],
    url: "https://www.zillow.com/homedetails/1130-Main-Dalton-Rd-Windsor-MA-01270/56820467_zpid/",
    notes: "Best acreage on the list — 9.11 acres. $182/sqft, taxes only $3,590/yr. Brook, mountain views, new deck, refinished hardwoods. 1BR/1BA first floor, primary + 2BR/1BA second floor. Dalton ~17 min, Pittsfield ~25-30 min. Budget $25-40k: mini-splits + 100→200-amp panel upgrade required.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-12"
  },
  {
    id: "1511-dunhamtown-brimfield-rd-brimfield-ma",
    address: "1511 Dunhamtown Brimfield Rd",
    town: "Brimfield",
    state: "MA",
    price: 469900,
    originalPrice: 499900,
    lat: 42.1237,
    lng: -72.2081,
    imageUrl: "https://photos.zillowstatic.com/fp/f236d1adf3f96a04e14aa023813f7983-cc_ft_960.webp",
    beds: 3,
    baths: 2,
    sqft: 2472,
    acres: 2,
    type: "Single family",
    status: "active",
    listedDate: "2026-04-15",
    hvac: "none",
    flags: ["Need ~$100k drop", "$30k price cut on 8/6: $499,900 → $469,900"],
    url: "https://www.zillow.com/homedetails/1511-Dunhamtown-Brimfield-Rd-Brimfield-MA-01010/56990110_zpid/",
    notes: "Natural floor split. Stream, solar panels, deck. Full 1993 time capsule — est. $60-80k cosmetic work needed. Oil baseboard, no ductwork, mini-splits needed. Watch for drop to ~$399,900.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-08-08"
  },
  {
    id: "763-stony-hill-rd-wilbraham-ma",
    address: "763 Stony Hill Rd",
    town: "Wilbraham",
    state: "MA",
    price: 485000,
    lat: 42.1112,
    lng: -72.437,
    imageUrl: "https://photos.zillowstatic.com/fp/0271b1d5066c69686f120d151ba2178b-cc_ft_960.webp",
    beds: 3,
    baths: 2,
    sqft: 1902,
    acres: 0.89,
    type: "Bungalow",
    status: "withdrawn",
    listedDate: "2025-12-01",
    hvac: "none",
    flags: ["Bundle target — watch prices", "No longer partner's favorite, but staying on the list — especially worth revisiting if the price drops further", "Off market as of 8/29 — removed from consideration"],
    url: "https://www.zillow.com/homedetails/763-Stony-Hill-Rd-Wilbraham-MA-01095/57000909_zpid/",
    notes: "Bungalow + detached studio w/ own kitchen, bath & laundry. 225+ days on market, low save ratio. Partner's top choice as a bundle: 763 ($485k) + adjacent 767 lot ($215k) = $700k combined ask. Target bundle price $560k — both sitting, seller motivated. Oil forced air + electric, no central air, mini-splits est. $15-25k.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-29"
  },
  {
    id: "100-heritage-dr-glastonbury-ct",
    address: "100 Heritage Dr",
    town: "Glastonbury",
    state: "CT",
    price: 517000,
    lat: 41.7162,
    lng: -72.6079,
    imageUrl: "https://ap.rdcpix.com/06d87ddeb2c47a1ec5dbf6dc204c3b82l-m2916698304rd-w960_h720.webp",
    beds: 3,
    baths: 3,
    sqft: 2288,
    acres: 1.59,
    type: "Ranch",
    status: "pending",
    hvac: "none",
    flags: ["Taxes $9,104/yr and climbing — ~$10k within 2 years at current rate", "Baseboard hot water, no ductwork — mini-splits from scratch ~$18-25k", "78.9% markup since 2019 ($289k → $517k)", "Market will likely decide this one quickly", "Now pending as of 7/27 — expected, market decided quickly", "REMOVED 8/24: Taxes too high"],
    url: "https://www.zillow.com/homedetails/100-Heritage-Dr-Glastonbury-CT-06033/174072472_zpid",
    notes: "Ranch with finished lower level. Great separation: main floor primary (remodeled en-suite) + 1BR + full bath; lower level 1BR + full bath + family room w/ fireplace. Central air. Vaulted ceilings, skylights, quartz kitchen, 2 fireplaces. 2-car garage, shed. Glastonbury — strong town, good infrastructure.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-24"
  },
  {
    id: "436-tiffany-ln-bristol-ct",
    address: "436 Tiffany Ln",
    town: "Bristol",
    state: "CT",
    price: 499900,
    originalPrice: 545000,
    lat: 41.6718,
    lng: -72.9493,
    imageUrl: "https://photos.zillowstatic.com/fp/085e36bfd2103c57462d993fc30b510e-cc_ft_960.webp",
    beds: 5,
    baths: 4,
    sqft: 3456,
    acres: 1.34,
    type: "Single family",
    status: "contingent",
    listedDate: "2026-06-20",
    hvac: "window",
    flags: ["Window units only — mini-splits needed both levels ~$25-35k", "Taxes $9,530/yr, climbing 6-8%/yr", "Pool sold As Is / needs liner", "28 days on market, 184 saves, no contract — market pricing in AC/tax issues, watch for a drop", "Now accepting backups as of 7/30", "Full cut history: $545k → $520k (8/8, -4.6%) → $499,900 (8/20)", "REMOVED 8/24: Too big"],
    url: "https://www.zillow.com/homedetails/436-Tiffany-Ln-Bristol-CT-06010/57704737_zpid/",
    notes: "Best in-law suite layout seen so far — lower level fully self-contained (BR, full bath, kitchen, living room, office, separate entrance). Upper level massive primary (13x19) + 3BR + 2 baths. Cul-de-sac, wooded, Cedar Lake neighborhood. Zestimate $546,300 — priced at fair value.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-24"
  },
  {
    id: "420-lower-hampden-rd-monson-ma",
    address: "420 Lower Hampden Rd",
    town: "Monson",
    state: "MA",
    price: 495000,
    lat: 42.0995,
    lng: -72.3162,
    imageUrl: "https://photos.zillowstatic.com/fp/8304983235c342dcb89959b620c100c9-cc_ft_960.webp",
    beds: 4,
    baths: 2,
    sqft: 1896,
    acres: 2.75,
    type: "Single family",
    status: "pending",
    listedDate: "2026-07-17",
    hvac: "central",
    flags: ["Inground pool — unwanted maintenance", "Pellet stove supplemental heat", "1,896 sqft modest for 4BR", "Low early engagement (6 saves in 16 hrs) — monitor", "Under contract as of 8/4 — removed from active consideration"],
    url: "https://www.zillow.com/homedetails/420-Lower-Hampden-Rd-Monson-MA-01057/193649080_zpid/",
    notes: "Good floor separation — 1BR/1BA first floor, primary + 2BR/1BA second floor. Central air. Solar (owned). Forced air oil, ductwork exists. 2.75 acres, scenic views, full-width covered porch, 3-season room. Taxes $5,638/yr — one of the lowest on the list. Zestimate $497k — fair value. Brand new listing, no prior price history.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-04"
  },
  {
    id: "577-579-old-greenwich-plains-rd-hardwick-ma",
    address: "577-579 Old Greenwich Plains Rd",
    town: "Hardwick",
    state: "MA",
    price: 500000,
    originalPrice: 550000,
    lat: 42.3468,
    lng: -72.1998,
    imageUrl: "https://photos.zillowstatic.com/fp/5e18e3963f66f900ad1204dd27005afb-cc_ft_960.webp",
    beds: 4,
    baths: 4,
    sqft: 3458,
    acres: 1.48,
    type: "Duplex (2-family)",
    status: "active",
    listedDate: "2026-06-03",
    hvac: "window",
    flags: ["Window units only — mini-splits both units ~$30-40k", "Baseboard propane heat", "Tenant in unit 2, $1,200/mo below market, 6+ yrs, month-to-month — 30 days notice sufficient in MA for owner-occupant, handle carefully", "Walk score 0 — car dependent", "$25K cut 7/31: $525k → $500k", "Consider if it drops to $400k. Concerned about flooding — worth checking flood zone/history before any offer"],
    url: "https://www.zillow.com/homedetails/577-579-Old-Greenwich-Plains-Rd-Hardwick-MA-01082/173774155_zpid/",
    notes: "True side-by-side duplex — perfect separation, each unit fully self-contained (2BR/1.5BA, full basement, attached garage, deck). Lowest taxes on the entire list at $4,388/yr. Wooded 1.48 acres, well-maintained. Ware ~10-15 min. Already had a $25k price drop. 2,318 sqft + 1,140 sqft finished basement.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-08-24"
  },
  {
    id: "151-pantry-rd-hatfield-ma",
    address: "151 Pantry Rd",
    town: "Hatfield",
    state: "MA",
    price: 459900,
    originalPrice: 489900,
    lat: 42.3751,
    lng: -72.5967,
    imageUrl: "https://photos.zillowstatic.com/fp/2ff923fd94cd15ece3d08786c8ab9cd5-cc_ft_960.webp",
    beds: 4,
    baths: 4,
    sqft: 2288,
    acres: 3.3,
    type: "Duplex (2-family)",
    status: "pending",
    hvac: "none",
    flags: ["Only 3 photos — may be hiding condition issues", "All electric baseboard heat, no AC listed at all — mini-splits both units ~$30-40k", "Slab foundation — no basement, limited hobby/workshop space", "Relisted with new MLS number after being pulled (orig. Sept 2025 $489,900, pulled April 2026) — second attempt", "1,069 views but only 52 saves — something may be deterring serious buyers", "Now pending as of 8/12"],
    url: "https://www.zillow.com/homedetails/151-Pantry-Rd-Hatfield-MA-01038/57015733_zpid/",
    notes: "True side-by-side duplex, no current tenants. Just over the Northampton line — prime Pioneer Valley location. 3.3 wooded acres, set back from road. Separate electric per unit. Taxes $5,633/yr. Zestimate $520,400 — priced $60k under estimated value.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-08-12"
  },
  {
    id: "23-s-mount-holyoke-dr-amherst-ma",
    address: "23 S Mount Holyoke Dr",
    town: "Amherst",
    state: "MA",
    price: 429000,
    originalPrice: 469000,
    lat: 42.3732,
    lng: -72.5199,
    imageUrl: "https://photos.zillowstatic.com/fp/77becfb983e847c8e3e8c157ae3710c3-cc_ft_768.webp",
    beds: 4,
    baths: 2,
    sqft: 1773,
    acres: 1.27,
    type: "Cape",
    status: "pending",
    hvac: "minisplit",
    flags: ["Former rental history — likely dated condition", "Very few listing photos — possibly hiding something", "No mention of updates", "Taxes $8,822/yr and climbing (Amherst premium)", "1964 build — mechanicals age unknown", "Will move fast in Amherst market", "$40k price cut on 8/4: $469,000 → $429,000", "Now pending as of 8/12", "REMOVED 8/24: Partner doesn't love it"],
    url: "https://www.zillow.com/homedetails/23-S-Mount-Holyoke-Dr-Amherst-MA-01002/56258132_zpid",
    notes: "Perfect floor separation — 2BR/1BA first floor, 2BR/1BA second floor. Mini-splits already installed (ductless). Forced air oil heat. 2 fireplaces, hardwood floors. Walkout unfinished basement. 1.27 acres, prime Pioneer Valley location. Priced $89k under Zestimate ($558,300) — unusual gap.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-24"
  },
  {
    id: "401-n-washington-st-belchertown-ma",
    address: "401 N Washington St",
    town: "Belchertown",
    state: "MA",
    price: 449900,
    lat: 42.2751,
    lng: -72.4062,
    imageUrl: "https://photos.zillowstatic.com/fp/9beaf0748b842fa27c8162e52bcfa569-cc_ft_768.webp",
    beds: 5,
    baths: 2,
    sqft: 2772,
    acres: 3.32,
    type: "Farmhouse",
    status: "active",
    listedDate: "2026-07-29",
    hvac: "none",
    flags: ["No cooling at all — mini-splits from scratch required", "Both baths on first floor — upstairs bedrooms bathless (2 baths downstairs helps but not ideal)", "1950 build with stone foundation — inspect carefully", "Verify garage bonus space use with town before advancing", "REMOVED 8/24: No bathroom upstairs — hard NO from partner"],
    url: "https://www.zillow.com/homedetails/401-N-Washington-Rd-Belchertown-MA-01007/57004666_zpid",
    notes: "Farmhouse on 3.32 acres — barn, garden, peach/apple trees. Both full baths + 2 BRs on first floor. 3 newly renovated BRs upstairs. Oversized 2-car garage with unfinished bonus space above — previously plumbed + electrical started, potential in-law/workshop/lapidary space. Zestimate $553,800 — priced $104k under estimated value. Taxes $5,176/yr. 42 photos, confident listing. Belchertown, Pioneer Valley. Moving fast.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-24"
  },
  {
    id: "1-lakeshore-dr-monson-ma",
    address: "1 Lakeshore Dr",
    town: "Monson",
    state: "MA",
    price: 465000,
    lat: 42.0995,
    lng: -72.3162,
    imageUrl: "https://photos.zillowstatic.com/fp/b8f31bdddd55c51b15c8f28385213a91-cc_ft_1536.jpg",
    beds: 4,
    baths: 3,
    sqft: 1596,
    acres: 1.38,
    type: "Cape",
    status: "active",
    listedDate: "2026-07-20",
    hvac: "central",
    flags: ["2023 distress sale at $152k origin (37% below 2011 price) — worth asking about", "2024 flip renovation → sold $439,900 → current owner relisting at $465k after 27 months", "Current seller is NOT the flipper — bought already-renovated house"],
    url: "https://www.zillow.com/homedetails/1-Lakeshore-Dr-Monson-MA-01057/193645544_zpid",
    notes: "Great layout — 2BR/1BA first floor, 2BR/1BA second floor. Half bath in basement. Central air, natural gas forced air, 200+ amp, solar panels. Private lake access (Pulpit Rock Lake) for Lakeshore Dr residents only. Composite deck, 1.38 acres. Taxes $5,530/yr. Moving fast — 93rd percentile for speed nearby.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-08-01"
  },
  {
    id: "12-stage-rd-westhampton-ma",
    address: "12 Stage Rd",
    town: "Westhampton",
    state: "MA",
    price: 350000,
    lat: 42.2626,
    lng: -72.7534,
    imageUrl: "https://photos.zillowstatic.com/fp/e76950f5718e2c27abadaa19a33e2b9c-cc_ft_1536.jpg",
    beds: 4,
    baths: 2,
    sqft: 1958,
    acres: 1,
    type: "Duplex (2-family, converted)",
    status: "pending",
    listedDate: "2026-07-31",
    hvac: "none",
    flags: ["No cooling at all — mini-splits from scratch needed in both units ~$25-35k", "Needs cosmetic updating", "Partial basement only — limited workshop space", "1956 single-level build", "Under contract as of 8/5 — removed from active consideration"],
    url: "https://www.zillow.com/homedetails/12-Stage-Rd-Westhampton-MA-01027/57029020_zpid",
    notes: "Legal two-family — 2BR per unit, genuine separation. New 4BR septic. Newer furnace, oil tank, well pressure tank, solar hot water. Attached greenhouse + beautiful gardens. Flexible floor plan (non-load bearing walls). Very private, wooded. Near Northampton. Taxes $5,206/yr. Zestimate $384,900 — priced $35k under. Brand new listing.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-05"
  },
  {
    id: "73-glendale-rd-hampden-ma",
    address: "73 Glendale Rd",
    town: "Hampden",
    state: "MA",
    price: 450000,
    lat: 42.0682,
    lng: -72.487,
    imageUrl: "https://photos.zillowstatic.com/fp/cc683b1e637313285b96f982ece8c773-p_f.jpg",
    beds: 3,
    baths: 2,
    sqft: 2280,
    acres: 0.71,
    type: "Cape",
    status: "active",
    hvac: "window",
    flags: ["Window units only — mini-splits needed throughout 3 levels ~$25-35k", "No bath on main floor", "Full walkout basement w/ garage access — unfinished, not photographed, but significant bonus space", "Potentially very useful for lapidary/rock tumbling setup", "REMOVED 8/24: No bathroom on main floor — same dealbreaker as N Washington St"],
    url: "https://www.zillow.com/homedetails/73-Glendale-Rd-Hampden-MA-01036/56173352_zpid",
    notes: "3-level cape. Floor 1: main living (kitchen, dining 25x15, living 25x13, mudroom, no bath). Floor 2: 2BR + full bath (7x7) — private zone. Floor 3: large open loft (listed as 3 \"primary bedrooms\" but really one open space) + primary bath + closet — workshop/lapidary/sleeping potential. Laughing Brook waterfront, composite deck, wooded 0.71 acres. Taxes $7,424/yr. Not a flip — bought 2019, legitimate ownership. 1,795 views/127 saves, moving fast.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-24"
  },
  {
    id: "129-upper-hampden-rd-monson-ma",
    address: "129 Upper Hampden Rd",
    town: "Monson",
    state: "MA",
    price: 499413,
    lat: 42.0995,
    lng: -72.3162,
    imageUrl: "https://photos.zillowstatic.com/fp/26b7692d34fb617a525a2fe6fdc44972-p_f.jpg",
    beds: 3,
    baths: 2,
    sqft: 1900,
    acres: 16.12,
    type: "Single family",
    status: "pending",
    hvac: "central",
    flags: ["1933 build — exceeds 75-year rule by 18 years", "Stone/block foundation with partial crawl space — moisture/structural inspection critical", "Partial crawl only, no real workshop/basement space", "$355k → $499,413 in 2.5 years (41% markup) on modest garage/driveway improvements — cosmetic work by prior owner", "Oddly specific price suggests payoff-based rather than market-based pricing", "19 days, 128 saves, no contract — age/foundation giving buyers pause", "Now pending as of 8/12"],
    url: "https://www.zillow.com/homedetails/129-Upper-Hampden-Rd-Monson-MA-01057/193645141_zpid",
    notes: "Perfect layout — 2BR/1BA first floor, primary suite + en-suite full bath second floor. Central air, 200+ amp + generator connection. Newly renovated garage (all new electrical). 16.12 level acres — trails, flat backyard, exceptional land. Monson location. Taxes $4,880/yr.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-08-12"
  },
  {
    id: "102-coy-hill-rd-west-warren-ma",
    address: "102 Coy Hill Rd",
    town: "West Warren",
    state: "MA",
    price: 429000,
    lat: 42.2074,
    lng: -72.2224,
    imageUrl: "https://photos.zillowstatic.com/fp/104f5945061f17d9f28ae45704a9e6cb-cc_ft_768.webp",
    beds: 4,
    baths: 2,
    sqft: 2648,
    acres: 1.27,
    type: "Ranch w/ in-law suite",
    status: "active",
    hvac: "minisplit",
    flags: ["63% flip markup in 14 months ($263k → $429k)", "Verify “legally permitted” in-law suite status with Warren building dept before advancing", "In-law suite cooling not mentioned — confirm mini-splits cover it or if more are needed", "Tepid engagement possibly location/season related (August doldrums)", "REMOVED 8/24: Neighbor too close"],
    url: "https://www.zillow.com/homedetails/102-Coy-Hill-Rd-West-Warren-MA-01083/57665273_zpid/",
    notes: "Legally permitted in-law suite — separate entrance, separate utilities, separate electric meter, full kitchen, full bath — best separation setup on the list. Mini-splits in main home. 24x24 detached garage (2009) — workshop potential. Ware hospital 4 miles away. Town water and sewer. Finished basement 1,104 sqft. Taxes $4,156/yr — very low. Listing photos are AI virtual staging of the empty house, not concealing damage.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-24"
  },
  {
    id: "259-greenwich-rd-ware-ma",
    address: "259 Greenwich Rd",
    town: "Ware",
    state: "MA",
    price: 499000,
    lat: 42.2626,
    lng: -72.2454,
    imageUrl: "https://photos.zillowstatic.com/fp/a5b267023c281ae401fd36f2fc626682-sc_1776_1184.webp",
    beds: 3,
    baths: 2,
    sqft: 1638,
    acres: 3.03,
    type: "Cape",
    status: "pending",
    listedDate: "2026-08-01",
    hvac: "none",
    flags: ["No AC — baseboard oil + wood stove only", "Mini-splits from scratch required ~$18-25k, complex with vaulted ceilings", "Bought $350k Jan 2021 → $499k Aug 2026 (42.6% markup)", "No garage", "Partner prefers ADU setup — this doesn't have one", "Watch if it sits; not an immediate jump-on-it given partner's ADU preference", "Now pending as of 8/20"],
    url: "https://www.zillow.com/homedetails/259-Greenwich-Rd-Ware-MA-01082/57026778_zpid",
    notes: "Stunning waterfront cape — brook access to Hardwick Pond, kayak from backyard. Gorgeous primary suite upstairs (19x20 + private bath + wood ceiling). 2BR/1BA on main floor — solid separation. Living room 18x28, custom kitchen with island/quartz/gas range. Full walkout basement — insulation boards mounted, unfinished but clearly finishable and structurally solid. 3.03 wooded acres, terraced stone gardens, fire pit, wraparound deck. Red barn/shed on property. Taxes $5,274/yr. Ware, hospital 4 miles. Flood risk low (First Street 1/10, no FEMA high-risk designation). 43 listing photos — confident listing.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-08-20"
  },
  {
    id: "276-old-gilbertville-rd-ware-ma",
    address: "276 Old Gilbertville Rd",
    town: "Ware",
    state: "MA",
    price: 529000,
    lat: 42.2626,
    lng: -72.2454,
    imageUrl: "https://photos.zillowstatic.com/fp/6ce8e29a2f0de49ec4977825fcffa17e-p_f.jpg",
    beds: 4,
    baths: 2,
    sqft: 2644,
    acres: 7.74,
    type: "Single family",
    status: "active",
    hvac: "central",
    flags: ["Offer fell through 8/17: no HVAC ducts in basement or attic, caught during the virtual showing (not visible in listing photos — no AC/condenser pic, and the stove pipe hole had been covered with painter's tape after listing photos were taken). Condenser also 27 years old, due for replacement. Offer reflected these issues; seller countered at full list, no movement."],
    url: "https://www.zillow.com/homedetails/276-Old-Gilbertville-Rd-Ware-MA-01082/57026767_zpid",
    notes: "Excellent layout — 3BR/1BA main floor (1 BR may be laundry/nonconforming), lower level suite (BR 11x13 + full bath 12x12 + rec room 29x26), upper loft/bonus room (28x11 + balcony) — perfect music/make space for partner. Central air. 7.74 acres, 7-stall barn + garage/workshop. Cathedral ceilings, new kitchen, refinished hardwoods, big deck. Taxes ~$4,900/yr.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-17"
  },
  {
    id: "79-pine-ridge-rd-montgomery-ma",
    address: "79 Pine Ridge Rd",
    town: "Montgomery",
    state: "MA",
    price: 515000,
    originalPrice: 560000,
    lat: 42.1373,
    lng: -72.8137,
    imageUrl: "https://photos.zillowstatic.com/fp/85aceb1fd56893739f9dd1e1edd1aedd-cc_ft_1536.jpg",
    beds: 4,
    baths: 3,
    sqft: 2324,
    acres: 2.82,
    type: "Contemporary",
    status: "active",
    listedDate: "2026-05-29",
    hvac: "central",
    flags: ["Only 14 photos — likely dated 1978 interior", "Nearly 1 year on market across 2 MLS numbers ($588k → current)", "DOM reset in May 2026 after being pulled Dec 2025", "Sitting at top of street comps", "Partial basement only", "Worth seeing in person given partner's interest — photos don't tell the full story here", "Confirmed cuts: $560k (5/29) → $549k (6/12) → $539k (7/8) → $525k (7/29)", "$10K cut 8/18: $525k → $515k", "REMOVED 8/24: Realtor owns the property and isn't forthcoming with layout/photos — can't get a real sense of the space"],
    url: "https://www.zillow.com/homedetails/79-Pine-Ridge-Rd-Montgomery-MA-01085/59246134_zpid/",
    notes: "Contemporary on 2.82 wooded acres abutting 1,200+ acres protected wildlife — exceptional privacy. Perfect separation: main floor primary suite (en-suite + walk-in closet) + 2BRs + full bath; upstairs 4th BR with skylight, cathedral ceiling, private full bath. Central air. Floor-to-ceiling fieldstone fireplace, vaulted ceilings, exposed beams, hardwood floors. 2-car garage. Taxes $5,211/yr. Montgomery near Westfield/I-90. Seller W/Participate = motivated, open to creative financing/negotiation.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-24"
  },
  {
    id: "222-granby-rd-belchertown-ma",
    address: "222 Granby Rd",
    town: "Belchertown",
    state: "MA",
    price: 529000,
    lat: 42.2751,
    lng: -72.4062,
    imageUrl: "https://photos.zillowstatic.com/fp/2078c9fecc43702d666d05bd1713dbb3-p_f.jpg",
    beds: 3,
    baths: 3,
    sqft: 2034,
    acres: 3.79,
    type: "Cape",
    status: "active",
    hvac: "central",
    flags: ["Verify solar owned vs. leased — not disclosed in listing", "Taxes climbing aggressively (assessed $500,400, up 8.4% last year)", "$260/sqft on the higher end for Belchertown", "43.6% markup over 7 years (not a flip — legitimate appreciation)"],
    url: "https://www.zillow.com/homedetails/222-Granby-Rd-Belchertown-MA-01007/67714343_zpid/",
    notes: "Cape, 2005 build. Clean separation — main floor primary suite (14x17, en-suite full bath + half bath) vs. upstairs 2BR (18x23 and 15x23) + double vanity full bath. Central air. Solar installed. Gas stove, skylights, vaulted ceilings. 2-car attached garage. 3.79 acres, fenced yard, fruit trees, deck/porch. Full walkout basement unfinished. Above ground pool removed. Partner find. Taxes $7,571/yr. Belchertown — good infrastructure, Baystate/Cooley Dickinson accessible. Title 5 required at sale (well + septic).",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-08-24"
  },
  {
    id: "70-high-st-monson-ma",
    address: "70 High St",
    town: "Monson",
    state: "MA",
    price: 479000,
    originalPrice: 499000,
    lat: 42.0995,
    lng: -72.3162,
    imageUrl: "https://photos.zillowstatic.com/fp/701ecd4d7ae50a4c71afeba85f1de0d3-cc_ft_960.webp",
    beds: 4,
    baths: 4,
    sqft: 2392,
    acres: 0.57,
    type: "Colonial",
    status: "active",
    hvac: "window",
    flags: ["Electric heat + window units — mini-splits needed", "0.57 acres (small but wooded setting feels larger)", "Corner lot", "$20k cut on 8/19 suggests some market hesitancy", "Seller is paying off the solar system for the buyer — resolves the owned vs. leased question", "Dropped 8/29: after checking local politics, decided to aim for a less conservative area (Monson specifically)"],
    url: "https://www.zillow.com/homedetails/70-High-St-Monson-MA-01057/193647283_zpid",
    notes: "Distinctive colonial on wooded hillside — wraparound dormers, partner loves it. Genuine separation: primary suite (cathedral ceiling, walk-in closet, balcony, en-suite full bath) + \"second master\" BR with own full bath. 2 additional BRs. Finished basement. Garage under main level. Large deck off second floor, balconies. Public water + sewer (no septic). 220V electric. Monson location.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-08-29"
  },
  {
    id: "78-oak-brook-dr-east-longmeadow-ma",
    address: "78 Oak Brook Dr",
    town: "East Longmeadow",
    state: "MA",
    price: 499000,
    lat: 42.0645,
    lng: -72.5054,
    imageUrl: "https://photos.zillowstatic.com/fp/595f7c10cf52067ea61ae5f556717f9b-p_e.webp",
    beds: 4,
    baths: 2,
    sqft: 1632,
    acres: 0.58,
    type: "Single family",
    status: "active",
    hvac: "window",
    flags: ["Window units only — mini-splits needed ~$15-20k, ductwork helps", "100 amp service — needs upgrade to 200 amp ~$3-6k before mini-splits", "Taxes $7,962/yr", "Sump pump disclosed", "Partner lukewarm — “if nothing else available” status", "Low save rate (36/917 views)"],
    url: "https://www.zillow.com/homedetails/78-Oak-Brook-Dr-East-Longmeadow-MA-01028/56169507_zpid/",
    notes: "Clever layout — main floor BR + full bath + basement bonus room (10x21) for Person 1; huge primary (11x23) + 2 BRs + full bath upstairs for Person 2; 3rd upstairs BR as shared office. Internal stairs connect all levels. Sunroom, hardwood floors, granite kitchen, large yard. Mature evergreen privacy screening on both sides. Sidewalks, East Longmeadow infrastructure. Baystate Medical ~15 min. Public water/sewer. Natural gas forced air (ductwork exists). One year home warranty included.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-08-26"
  },
  {
    id: "123-saunders-st-gardner-ma",
    address: "123 Saunders St",
    town: "Gardner",
    state: "MA",
    price: 519900,
    lat: 42.56399,
    lng: -71.964226,
    imageUrl: "https://photos.zillowstatic.com/fp/c07a8bd29b0841f80649adc5daf2023a-cc_ft_1536.jpg",
    beds: 3,
    baths: 2,
    sqft: 2102,
    acres: 3.5,
    type: "Cape",
    status: "active",
    listedDate: "2026-08-25",
    hvac: "none",
    flags: ["No central air — whole house fan only, mini-splits would be needed", "Gardner GreatSchools ratings are low (2-4/10) — worth noting even without school-age considerations, can affect resale", "Walk Score 7/100 — fully car-dependent", "Heat is baseboard oil + wood, not forced air"],
    url: "https://www.zillow.com/homedetails/123-Saunders-St-Gardner-MA-01440/57588581_zpid",
    notes: "First and only listing by original owner since 1986 — not a flip, well-loved home. Good separation: primary BR (23x13) + full bath on first floor; 2 BRs + full bath on second floor. Full unfinished basement — workshop potential. 2-car attached garage. 3.5 wooded acres, long private paved drive. 200+ amp. Passed Title 5. Taxes $6,060/yr — very reasonable. Zestimate $517,400 — priced at fair value. 42 photos, confident listing. Partner drove through area and likes it — Leominster (~15-20 min) as infrastructure hub, HealthAlliance Hospital in Leominster + UMass Medical Worcester as backup.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-08-27"
  },
  {
    id: "634-glendale-rd-wilbraham-ma",
    address: "634 Glendale Rd",
    town: "Wilbraham",
    state: "MA",
    price: 539000,
    lat: 42.1112,
    lng: -72.437,
    imageUrl: "https://photos.zillowstatic.com/fp/3b1943a8a9ae9a258f5e8e1eae824a33-p_f.jpg",
    beds: 4,
    baths: 2,
    sqft: 1858,
    acres: 5,
    type: "Cape",
    status: "active",
    hvac: "central",
    flags: ["1940 build on block foundation — exceeds 75-year rule, careful inspection needed", "“Formerly finished” basement — likely moisture event, now unfinished", "Pool sold AS-IS, not opened in years — budget $5-15k remediation or removal", "Demolished outbuilding/shed AS-IS — remnants unknown", "Dining room slider sealed closed — ask why", "Very low engagement (11 saves in 2 days)", "One-day pull/relist Aug 26-27 — ask agent why", "Seller disclosures: pool not opened in years (AS-IS), outbuilding/shed demolished (AS-IS), extra slate pavers remain, dining room slider sealed closed. Seller-stated updates: HVAC (2014); water heater, septic, refinished hardwoods, interior paint, family room vinyl flooring + rear windows (all 2026). Living area figure excludes the partially finished walkout basement."],
    url: "https://www.zillow.com/homedetails/634-Glendale-Rd-Wilbraham-MA-01095/56999385_zpid/",
    notes: "Classic New England Cape on 5 acres abutting conservation land — nobody builds behind you ever. Perfect separation: 2BR/1BA main floor, 2BR/1BA second floor (one BR has fireplace + rooftop patio). Central air, 200+ amp. 3 fireplaces. 2-car attached garage. Refinished hardwoods, arched doorways, slate/stone den. Title 5 Certificate of Compliance. Wilbraham — Springfield suburbs sweet spot, Baystate Medical close, good politics. Taxes $7,263/yr.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-08-28"
  }
];