// ============================================================
// PROPERTY DATA
// ------------------------------------------------------------
// This is the file you'll edit as properties come and go.
// Each listing is one object in the LISTINGS array below.
//
// FIELD REFERENCE:
//   id        - unique slug, e.g. "48-case-rd-burlington-ct"
//   address   - street address
//   town      - town/city name
//   state     - "CT" or "MA"
//   price     - number, no $ or commas (current asking price)
//   originalPrice - number, optional. Set this if the price has been cut
//               since you first saw it. Omit it entirely if there's been
//               no change — don't set it equal to price.
//   lat, lng  - decimal coordinates, used for the Map tab. Easiest way to
//               get these: right-click the spot on Google Maps and click
//               the coordinates that pop up at the top — it copies them.
//   imageUrl  - optional. Direct link to the listing's first photo. On a
//               Zillow page, right-click the first photo and "Copy image
//               address" — or ask Claude to pull it from the og:image tag.
//               Omit if you don't have one; the card just skips the photo.
//   beds      - number
//   baths     - number
//   sqft      - number
//   acres     - number (decimal ok)
//   type      - free text, e.g. "Single family", "Cape"
//   status    - "active" | "pending" | "contingent" | "sold"
//   listedDate- "YYYY-MM-DD"
//   hvac      - "central" | "minisplit" | "window" | "none"
//               (central/minisplit = good, window = warning, none = bad)
//   flags     - array of short strings, e.g. ["unpermitted addition"]
//   url       - listing URL (Zillow/Realtor.com/etc.)
//   notes     - free text, shows on the card
//   watchlist - true/false — whether this is a saved favorite
//   dismissed - true/false — whether this has been passed on
//   lastChecked - "YYYY-MM-DD", optional. The date you (or Claude) last
//               confirmed this listing's status directly on Zillow/Realtor.
//               Cards flag themselves once this gets older than 14 days —
//               a direct response to a couple of stale reads that caused
//               confusion this week.
// ============================================================

const LISTINGS = [
  {
    id: "101-abbey-rd-east-hampton-ct",
    address: "101 Abbey Rd",
    town: "East Hampton",
    state: "CT",
    price: 439900,
    lat: 41.5734,
    lng: -72.4979,
    imageUrl: "https://photos.zillowstatic.com/fp/583d29cbeae84bdc3d1c73a101fa0852-cc_ft_960.webp",
    beds: 4,
    baths: 2,
    sqft: 2427,
    acres: 1.06,
    type: "Cape",
    status: "active",
    listedDate: "2026-07-16",
    hvac: "window",
    flags: ["Strong interest — 1,578 views / 126 saves as of day 2"],
    url: "https://www.zillow.com/homedetails/101-Abbey-Rd-East-Hampton-CT-06424/57853768_zpid/",
    notes: "Cape near Middletown. Main floor bed+bath, upstairs primary + 2 more beds. New septic + updated electrical. Window units only, mini-splits needed. Note: Zillow briefly showed this as off-market on 7/18 — confirmed still active; Zillow status/Zestimate can lag a few days.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  },
  {
    id: "181-moulton-hill-rd-monson-ma",
    address: "181 Moulton Hill Rd",
    town: "Monson",
    state: "MA",
    price: 539800,
    lat: 42.0995,
    lng: -72.3162,
    imageUrl: "https://photos.zillowstatic.com/fp/9de4311b17c455f636f6c9f82541f7ba-cc_ft_960.webp",
    beds: 4,
    baths: 2,
    sqft: 2047,
    acres: 2,
    type: "Colonial",
    status: "contingent",
    listedDate: "2026-07-15",
    hvac: "central",
    flags: ["Move fast — will go quickly", "Under contract as of 7/20 — went fast as expected"],
    url: "https://www.zillow.com/homedetails/181-Moulton-Hill-Rd-Monson-MA-01057/193645908_zpid/",
    notes: "Built 2009, clean modern systems. Perfect split: 2BR/1BA first floor + 2BR/1BA second floor. Central air. Walkout basement unfinished. 2-car garage + 6 parking. Taxes $6,760/yr.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-07-20"
  },
  {
    id: "67-bell-st-middletown-ct",
    address: "67 Bell St",
    town: "Middletown",
    state: "CT",
    price: 499900,
    lat: 41.5623,
    lng: -72.6506,
    imageUrl: "https://photos.zillowstatic.com/fp/99036c74697e2b0b08c21a1d4806caa2-cc_ft_1536.jpg",
    beds: 3,
    baths: 2,
    sqft: 1576,
    acres: 4.6,
    type: "Single family",
    status: "contingent",
    listedDate: "2026-06-23",
    hvac: "none",
    flags: ["Verify solar if it relists"],
    url: "https://www.zillow.com/homedetails/67-Bell-St-Middletown-CT-06457/57866674_zpid/",
    notes: "Good separation: main floor primary + 1BR, lower level 1BR w/ own full bath. Right in Middletown. 4.6 acres, barn/stable. Sold $248k in 2019 → $499,900 now. No central air. Unpermitted/undisclosed solar — verify owned vs leased. Taxes $8,421/yr.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  },
  {
    id: "48-case-rd-burlington-ct",
    address: "48 Case Rd",
    town: "Burlington",
    state: "CT",
    price: 469000,
    originalPrice: 489000,
    lat: 41.7615,
    lng: -72.9587,
    imageUrl: "https://photos.zillowstatic.com/fp/f360f35d884f0ca0e40b6ed6493c1112-cc_ft_1536.jpg",
    beds: 4,
    baths: 3,
    sqft: 1929,
    acres: 1.02,
    type: "Colonial",
    status: "active",
    listedDate: "2026-06-18",
    hvac: "central",
    flags: ["Deal fell through — ask why"],
    url: "https://www.zillow.com/homedetails/48-Case-Rd-Burlington-CT-06013/57706189_zpid/",
    notes: "2BR/2BA main floor — natural two-person separation. 2BR/1BA upstairs bonus space. Oil forced air + central air. Solar — verify owned vs PPA/leased. Reactivated after prior contract fell through.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  },
  {
    id: "235-middle-haddam-rd-east-hampton-ct",
    address: "235 Middle Haddam Rd",
    town: "East Hampton",
    state: "CT",
    price: 479900,
    lat: 41.5734,
    lng: -72.4979,
    imageUrl: "https://photos.zillowstatic.com/fp/2a68c6fd99ac9f96795141ff2e234fe3-cc_ft_1536.jpg",
    beds: 4,
    baths: 2,
    sqft: 1923,
    acres: 1.2,
    type: "Log Cabin",
    status: "contingent",
    listedDate: "2026-06-13",
    hvac: "central",
    flags: ["Run permit check first"],
    url: "https://www.zillow.com/homedetails/235-Middle-Haddam-Rd-E-Middle-Haddam-CT-06456/463217927_zpid/",
    notes: "Log cabin construction, two stone fireplaces, wraparound porch. Detached 2-car garage w/ loft + heater — workshop potential. Next to Hurd State Park, ~15-18 min to Middletown. Main level 2BR/1BA + upper 2BR/1BA. Central air + whole-house Generac. Taxes $7,400/yr. Accepting backups.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  },
  {
    id: "3-gretl-ln-new-milford-ct",
    address: "3 Gretl Ln",
    town: "New Milford",
    state: "CT",
    price: 479000,
    lat: 41.5793,
    lng: -73.4087,
    imageUrl: "https://photos.zillowstatic.com/fp/4f2aff2770ad6612ab8e8212044265fd-cc_ft_1536.jpg",
    beds: 4,
    baths: 2,
    sqft: 1908,
    acres: 1.08,
    type: "Raised Ranch",
    status: "contingent",
    listedDate: "2026-06-07",
    hvac: "window",
    flags: ["Accepting backups — watch for relist"],
    url: "https://www.zillow.com/homedetails/3-Gretl-Ln-New-Milford-CT-06776/58863029_zpid/",
    notes: "Built 1975, updated interior, refinished hardwoods. Lower level 12x15 BR + family room walkout. New furnace + HWH. Near Candlewood Lake. 2020 sale had same contingent→fall-through→relist pattern. Window units, mini-splits needed ~$18-25k.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  },
  {
    id: "200-bucks-hill-rd-southbury-ct",
    address: "200 Bucks Hill Rd",
    town: "Southbury",
    state: "CT",
    price: 499900,
    lat: 41.4837,
    lng: -73.2098,
    imageUrl: "https://photos.zillowstatic.com/fp/57b38a8ced25bbd30a235cb98cc95434-cc_ft_1536.jpg",
    beds: 3,
    baths: 2,
    sqft: 2360,
    acres: 1.53,
    type: "Cape",
    status: "contingent",
    listedDate: "2026-05-28",
    hvac: "window",
    flags: ["Accepting backups"],
    url: "https://www.zillow.com/homedetails/200-Bucks-Hill-Rd-Southbury-CT-06488/57991955_zpid/",
    notes: "3-level Cape — main floor primary suite, upper 2 large beds + full bath, basement family room. New 3-zone Burnham boiler. New roof 2022. Failed at $479,900 in 2023. Window units, mini-splits needed ~$15-25k.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  },
  {
    id: "143-belleview-ave-southington-ct",
    address: "143 Belleview Ave",
    town: "Southington",
    state: "CT",
    price: 539900,
    lat: 41.5998,
    lng: -72.8781,
    imageUrl: "https://photos.zillowstatic.com/fp/182e73de1b9a04e11b9666b4a58b44b0-cc_ft_1536.jpg",
    beds: 3,
    baths: 2,
    sqft: 2148,
    acres: 1.09,
    type: "Cape",
    status: "active",
    listedDate: "2026-06-05",
    hvac: "central",
    flags: ["Check layout — photos now live"],
    url: "https://www.zillow.com/homedetails/143-Belleview-Ave-Southington-CT-06489/174097245_zpid/",
    notes: "Built 1954, 1.09 acres. Natural gas + central air — best fuel combo. All bedrooms upstairs — layout concern for two-person separation.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  },
  {
    id: "541-middlebury-rd-watertown-ct",
    address: "541 Middlebury Rd",
    town: "Watertown",
    state: "CT",
    price: 499900,
    lat: 41.6032,
    lng: -73.1187,
    imageUrl: "https://photos.zillowstatic.com/fp/96b057c422d21863764e308fad556903-cc_ft_1536.jpg",
    beds: 4,
    baths: 4,
    sqft: 2496,
    acres: 1.04,
    type: "Colonial",
    status: "active",
    listedDate: "2026-05-23",
    hvac: "central",
    flags: [],
    url: "https://www.zillow.com/homedetails/541-Middlebury-Road-Watertown-CT-06795/58870675_zpid/",
    notes: "Masonry fireplace, hardwood throughout, French doors. Finished lower level w/ full bath + walkout. Primary suite upstairs. Oil baseboard + central air. Septic 2002 — aging. Verify water district — Watertown Fire District preferred over Waterbury system.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  },
  {
    id: "80-old-baird-rd-watertown-ct",
    address: "80 Old Baird Rd",
    town: "Watertown",
    state: "CT",
    price: 525000,
    lat: 41.6032,
    lng: -73.1187,
    imageUrl: "https://photos.zillowstatic.com/fp/3947fc2eb10d03b3f35bb94e58800cb5-cc_ft_1536.jpg",
    beds: 3,
    baths: 3,
    sqft: null,
    acres: 1.78,
    type: "Craftsman Cape",
    status: "pending",
    listedDate: "2026-05-23",
    hvac: "central",
    flags: ["Pending as of Thursday 7/16 — off the table"],
    url: "https://www.zillow.com/homedetails/80-Old-Baird-Rd-Watertown-CT-06795/197756999_zpid/",
    notes: "Viking appliances, stone fireplace, cathedral ceilings. Each upstairs bedroom has own en-suite bath. Main floor 3rd bed + full bath. Propane baseboard + central air. Dead-end road, 1.78 acres. Accepting backups — watch for relist.",
    watchlist: true,
    dismissed: true,
    lastChecked: "2026-07-18"
  },
  {
    id: "392-boston-neck-rd-suffield-ct",
    address: "392 Boston Neck Rd",
    town: "Suffield",
    state: "CT",
    price: 399900,
    lat: 41.9812,
    lng: -72.6482,
    imageUrl: "https://photos.zillowstatic.com/fp/1b4bbf0b5d50fdc925ec594668fc17fc-cc_ft_1536.jpg",
    beds: 4,
    baths: 2,
    sqft: 2444,
    acres: 1.32,
    type: "Antique Colonial",
    status: "active",
    listedDate: "2026-03-15",
    hvac: "central",
    flags: ["1755 origin — inspect carefully"],
    url: "https://www.zillow.com/homedetails/392-Boston-Neck-Rd-Suffield-CT-06078/59024451_zpid/",
    notes: "Built 1755 original, substantially renovated. $40k drop — likely long-term family estate. Clean permit history — all Complete in ViewMyPermitCT. Oil hot water + central air.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  },
  {
    id: "76-clark-hill-rd-prospect-ct",
    address: "76 Clark Hill Rd",
    town: "Prospect",
    state: "CT",
    price: 499000,
    lat: 41.5029,
    lng: -72.9662,
    imageUrl: "https://photos.zillowstatic.com/fp/bfff281da1f881dce29f36f4c1ac39ee-cc_ft_960.webp",
    beds: 4,
    baths: 3,
    sqft: 3150,
    acres: 2.03,
    type: "Single family",
    status: "pending",
    listedDate: "2026-02-15",
    hvac: "central",
    flags: ["Now pending"],
    url: "https://www.zillow.com/homedetails/76-Clark-Hill-Rd-Prospect-CT-06712/57985177_zpid/",
    notes: "Level lot, 2+ acres, 2-car garage, 3,150 sqft — needs renovation. Oil hot air + central air. Sitting on market.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  },
  {
    id: "55-southampton-rd-westhampton-ma",
    address: "55 Southampton Rd",
    town: "Westhampton",
    state: "MA",
    price: 525000,
    lat: 42.2626,
    lng: -72.7534,
    imageUrl: "https://photos.zillowstatic.com/fp/fcb7c64326c1649d88a9b827b3040588-cc_ft_960.webp",
    beds: 4,
    baths: 2,
    sqft: 1944,
    acres: 1.21,
    type: "Single family",
    status: "active",
    listedDate: "2026-06-20",
    hvac: "window",
    flags: ["Verify ownership history"],
    url: "https://www.zillow.com/homedetails/55-Southampton-Rd-Westhampton-MA-01027/57028999_zpid/",
    notes: "Brook access, greenhouse, gardens, dog run. 2BR main floor incl. primary suite + 1BR upstairs — reasonable separation. Taxes only $5,572/yr, near Northampton. Electric heat + pellet stoves, window units only. Listed 2018 at $339,900 (didn't sell), no recorded sale since — ask agent about ownership gap.",
    watchlist: true,
    dismissed: false
  },
  {
    id: "68-lyon-rd-west-brookfield-ma",
    address: "68 Lyon Rd",
    town: "West Brookfield",
    state: "MA",
    price: 495000,
    originalPrice: 525000,
    lat: 42.2382,
    lng: -72.1512,
    imageUrl: "https://photos.zillowstatic.com/fp/154e75b246dd49eb835d06a54c0d6534-cc_ft_960.webp",
    beds: 3,
    baths: 2,
    sqft: 2280,
    acres: 1.81,
    type: "Single family w/ ADU",
    status: "active",
    listedDate: "2026-06-14",
    hvac: "none",
    flags: ["Not move-in ready — watch for more drops"],
    url: "https://www.zillow.com/homedetails/68-Lyon-Rd-West-Brookfield-MA-01585/57673905_zpid/",
    notes: "ADU layout: upper 3BR + half bath + kitchen/living, lower BR + full bath + kitchenette + 2 bonus rooms. 3-car detached garage w/ upper room — workshop potential. Ware 9 min. NOT move-in ready — bare subfloor, unfinished drywall. Electric radiant heat needs full overhaul, ~$20-30k. Watch for drop toward $459-465k.",
    watchlist: true,
    dismissed: false
  },
  {
    id: "1130-main-dalton-rd-windsor-ma",
    address: "1130 Main Dalton Rd",
    town: "Windsor",
    state: "MA",
    price: 474900,
    lat: 42.5262,
    lng: -73.0231,
    imageUrl: "https://photos.zillowstatic.com/fp/4d7e0a71811ab80dcb28ec75895732f6-cc_ft_960.webp",
    beds: 4,
    baths: 2,
    sqft: 2616,
    acres: 9.11,
    type: "Single family",
    status: "active",
    listedDate: "2026-06-10",
    hvac: "none",
    flags: ["Panel upgrade + mini-splits needed"],
    url: "https://www.zillow.com/homedetails/1130-Main-Dalton-Rd-Windsor-MA-01270/56820467_zpid/",
    notes: "Best acreage on the list — 9.11 acres. $182/sqft, taxes only $3,590/yr. Brook, mountain views, new deck, refinished hardwoods. 1BR/1BA first floor, primary + 2BR/1BA second floor. Dalton ~17 min, Pittsfield ~25-30 min. Budget $25-40k: mini-splits + 100→200-amp panel upgrade required.",
    watchlist: true,
    dismissed: false
  },
  {
    id: "1511-dunhamtown-brimfield-rd-brimfield-ma",
    address: "1511 Dunhamtown Brimfield Rd",
    town: "Brimfield",
    state: "MA",
    price: 499900,
    lat: 42.1237,
    lng: -72.2081,
    imageUrl: "https://photos.zillowstatic.com/fp/f236d1adf3f96a04e14aa023813f7983-cc_ft_960.webp",
    beds: 3,
    baths: 2,
    sqft: 2472,
    acres: 2,
    type: "Single family",
    status: "active",
    listedDate: "2026-04-15",
    hvac: "none",
    flags: ["Need ~$100k drop"],
    url: "https://www.zillow.com/homedetails/1511-Dunhamtown-Brimfield-Rd-Brimfield-MA-01010/56990110_zpid/",
    notes: "Natural floor split. Stream, solar panels, deck. Full 1993 time capsule — est. $60-80k cosmetic work needed. Oil baseboard, no ductwork, mini-splits needed. Watch for drop to ~$399,900.",
    watchlist: true,
    dismissed: false
  },
  {
    id: "763-stony-hill-rd-wilbraham-ma",
    address: "763 Stony Hill Rd",
    town: "Wilbraham",
    state: "MA",
    price: 485000,
    lat: 42.1112,
    lng: -72.437,
    imageUrl: "https://photos.zillowstatic.com/fp/0271b1d5066c69686f120d151ba2178b-cc_ft_960.webp",
    beds: 3,
    baths: 2,
    sqft: 1902,
    acres: 0.89,
    type: "Bungalow",
    status: "active",
    listedDate: "2025-12-01",
    hvac: "none",
    flags: ["Bundle target — watch prices"],
    url: "https://www.zillow.com/homedetails/763-Stony-Hill-Rd-Wilbraham-MA-01095/57000909_zpid/",
    notes: "Bungalow + detached studio w/ own kitchen, bath & laundry. 225+ days on market, low save ratio. Partner's top choice as a bundle: 763 ($485k) + adjacent 767 lot ($215k) = $700k combined ask. Target bundle price $560k — both sitting, seller motivated. Oil forced air + electric, no central air, mini-splits est. $15-25k.",
    watchlist: true,
    dismissed: false
  },
  {
    id: "100-heritage-dr-glastonbury-ct",
    address: "100 Heritage Dr",
    town: "Glastonbury",
    state: "CT",
    price: 517000,
    lat: 41.7162,
    lng: -72.6079,
    imageUrl: "https://ap.rdcpix.com/06d87ddeb2c47a1ec5dbf6dc204c3b82l-m2916698304rd-w960_h720.webp",
    beds: 3,
    baths: 3,
    sqft: 2288,
    acres: 1.59,
    type: "Ranch",
    status: "active",
    hvac: "none",
    flags: ["Taxes $9,104/yr and climbing — ~$10k within 2 years at current rate", "Baseboard hot water, no ductwork — mini-splits from scratch ~$18-25k", "78.9% markup since 2019 ($289k → $517k)", "Market will likely decide this one quickly"],
    url: "https://www.zillow.com/homedetails/100-Heritage-Dr-Glastonbury-CT-06033/174072472_zpid",
    notes: "Ranch with finished lower level. Great separation: main floor primary (remodeled en-suite) + 1BR + full bath; lower level 1BR + full bath + family room w/ fireplace. Central air. Vaulted ceilings, skylights, quartz kitchen, 2 fireplaces. 2-car garage, shed. Glastonbury — strong town, good infrastructure.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  },
  {
    id: "436-tiffany-ln-bristol-ct",
    address: "436 Tiffany Ln",
    town: "Bristol",
    state: "CT",
    price: 545000,
    lat: 41.6718,
    lng: -72.9493,
    imageUrl: "https://photos.zillowstatic.com/fp/085e36bfd2103c57462d993fc30b510e-cc_ft_960.webp",
    beds: 5,
    baths: 4,
    sqft: 3456,
    acres: 1.34,
    type: "Single family",
    status: "active",
    listedDate: "2026-06-20",
    hvac: "window",
    flags: ["Window units only — mini-splits needed both levels ~$25-35k", "Taxes $9,530/yr, climbing 6-8%/yr", "Pool sold As Is / needs liner", "28 days on market, 184 saves, no contract — market pricing in AC/tax issues, watch for a drop"],
    url: "https://www.zillow.com/homedetails/436-Tiffany-Ln-Bristol-CT-06010/57704737_zpid/",
    notes: "Best in-law suite layout seen so far — lower level fully self-contained (BR, full bath, kitchen, living room, office, separate entrance). Upper level massive primary (13x19) + 3BR + 2 baths. Cul-de-sac, wooded, Cedar Lake neighborhood. Zestimate $546,300 — priced at fair value.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  },
  {
    id: "420-lower-hampden-rd-monson-ma",
    address: "420 Lower Hampden Rd",
    town: "Monson",
    state: "MA",
    price: 495000,
    lat: 42.0995,
    lng: -72.3162,
    imageUrl: "https://photos.zillowstatic.com/fp/8304983235c342dcb89959b620c100c9-cc_ft_960.webp",
    beds: 4,
    baths: 2,
    sqft: 1896,
    acres: 2.75,
    type: "Single family",
    status: "active",
    listedDate: "2026-07-17",
    hvac: "central",
    flags: ["Inground pool — unwanted maintenance", "Pellet stove supplemental heat", "1,896 sqft modest for 4BR", "Low early engagement (6 saves in 16 hrs) — monitor"],
    url: "https://www.zillow.com/homedetails/420-Lower-Hampden-Rd-Monson-MA-01057/193649080_zpid/",
    notes: "Good floor separation — 1BR/1BA first floor, primary + 2BR/1BA second floor. Central air. Solar (owned). Forced air oil, ductwork exists. 2.75 acres, scenic views, full-width covered porch, 3-season room. Taxes $5,638/yr — one of the lowest on the list. Zestimate $497k — fair value. Brand new listing, no prior price history.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  },
  {
    id: "577-579-old-greenwich-plains-rd-hardwick-ma",
    address: "577-579 Old Greenwich Plains Rd",
    town: "Hardwick",
    state: "MA",
    price: 525000,
    originalPrice: 550000,
    lat: 42.3468,
    lng: -72.1998,
    imageUrl: "https://photos.zillowstatic.com/fp/5e18e3963f66f900ad1204dd27005afb-cc_ft_960.webp",
    beds: 4,
    baths: 4,
    sqft: 3458,
    acres: 1.48,
    type: "Duplex (2-family)",
    status: "active",
    listedDate: "2026-06-03",
    hvac: "window",
    flags: ["Window units only — mini-splits both units ~$30-40k", "Baseboard propane heat", "Tenant in unit 2, $1,200/mo below market, 6+ yrs, month-to-month — 30 days notice sufficient in MA for owner-occupant, handle carefully", "Walk score 0 — car dependent"],
    url: "https://www.zillow.com/homedetails/577-579-Old-Greenwich-Plains-Rd-Hardwick-MA-01082/173774155_zpid/",
    notes: "True side-by-side duplex — perfect separation, each unit fully self-contained (2BR/1.5BA, full basement, attached garage, deck). Lowest taxes on the entire list at $4,388/yr. Wooded 1.48 acres, well-maintained. Ware ~10-15 min. Already had a $25k price drop. 2,318 sqft + 1,140 sqft finished basement.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  },
  {
    id: "151-pantry-rd-hatfield-ma",
    address: "151 Pantry Rd",
    town: "Hatfield",
    state: "MA",
    price: 459900,
    originalPrice: 489900,
    lat: 42.3751,
    lng: -72.5967,
    imageUrl: "https://photos.zillowstatic.com/fp/2ff923fd94cd15ece3d08786c8ab9cd5-cc_ft_960.webp",
    beds: 4,
    baths: 4,
    sqft: 2288,
    acres: 3.3,
    type: "Duplex (2-family)",
    status: "active",
    hvac: "none",
    flags: ["Only 3 photos — may be hiding condition issues", "All electric baseboard heat, no AC listed at all — mini-splits both units ~$30-40k", "Slab foundation — no basement, limited hobby/workshop space", "Relisted with new MLS number after being pulled (orig. Sept 2025 $489,900, pulled April 2026) — second attempt", "1,069 views but only 52 saves — something may be deterring serious buyers"],
    url: "https://www.zillow.com/homedetails/151-Pantry-Rd-Hatfield-MA-01038/57015733_zpid/",
    notes: "True side-by-side duplex, no current tenants. Just over the Northampton line — prime Pioneer Valley location. 3.3 wooded acres, set back from road. Separate electric per unit. Taxes $5,633/yr. Zestimate $520,400 — priced $60k under estimated value.",
    watchlist: true,
    dismissed: false,
    lastChecked: "2026-07-18"
  }
];